name: Deploy to EC2 via SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      # Step 3: Configure AWS credentials using GitHub Secrets
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region <your-aws-region>

      # Step 4: Use AWS SSM to deploy code to EC2 instance
      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids "your-instance-id" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying Neve Child Theme" \
            --parameters commands="cd /path/to/wordpress/wp-content/themes/neve-child && git pull origin main" \
            --output text
